# Generated by Django 5.1 on 2024-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('banner', models.ImageField(upload_to='banner/', verbose_name='Баннер сайта')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('watermark', models.CharField(max_length=50, verbose_name='Водяной знак')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
