# Generated by Django 5.1 on 2024-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurultai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Добавить изменения'},
        ),
        migrations.AddField(
            model_name='settings',
            name='about',
            field=models.CharField(max_length=20, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='about_us',
            field=models.TextField(null=True, verbose_name='Текст для второго заголовка'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(verbose_name='Что за изменение?'),
        ),
    ]
