# Generated by Django 5.1 on 2024-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurultai', '0002_alter_settings_options_settings_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_team', models.ImageField(upload_to='photo_team/', verbose_name='Фото участника (в формате 337/667)')),
                ('fullname', models.CharField(max_length=50, verbose_name='ФИО участника')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Добавление участника',
                'verbose_name_plural': 'Добавить участника',
            },
        ),
    ]
