# Generated by Django 5.1 on 2024-09-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qurultai', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='banner',
        ),
    ]
