# Generated by Django 5.1 on 2024-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurultai', '0005_settings_email_settings_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_end',
            field=models.CharField(max_length=50, verbose_name='Текст в конце'),
        ),
    ]
